### ISSUE TITLE
Install failed

### ISSUE THREAD

**Issue by sgyur** [abey79/hatched#12]
Hi,

I'm unable to get the install to work. I get the following message: 

`Collecting Shapely[vectorized]==1.8.0
  Using cached Shapely-1.8.0.tar.gz (278 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.`

Any thoughts? I'm setting up a venv in conda and using the pip command provided. I successfully installed Shapely independently afterwards thinking that might solve the issue but the general install still stalls. Thanks!

**Comment by mariana-s-fernandes** [comment]
No idea of what is happening, but I don't trust conda. Me and other people I know have had some issues with it in the past and I recommend uninstalling it completely and use pip instead.

**Comment by abey79** [comment]
As @mariana-s-fernandes said. I've had all but issues with conda.
