### ISSUE TITLE
Feature request: control angle of line hatching

### ISSUE THREAD

**Issue by jimmykl** [abey79/hatched#2]
It would be useful to be able to set the angle for the hatched lines

And cool to be able to vary / modulate the angle too but let's not get ahead of ourselves 😆

**Comment by mariana-s-fernandes** [comment]
+1 this would be super cool!

**Comment by mariana-s-fernandes** [comment]
I have implemented this locally, I need to test and will open a PR soon.

**Comment by mariana-s-fernandes** [comment]
This one can be closed as per https://github.com/plottertools/hatched/pull/7
