### ISSUE TITLE
New idea for hatched

### ISSUE THREAD

**Issue by joker999** [abey79/hatched#4]
I wonder if you can make x,y for circular, not always the middle of the art work.
Also CMYK  layer?
Thanks :)

**Comment by abey79** [comment]
> I wonder if you can make x,y for circular, not always the middle of the art work.

I'm not sure what you mean exactly. Can you expand?

> Also CMYK layer?

This can already be achieved if you separate your input file with another software (gimp, imagemagick, etc.).

Then:

```
vpype hatched --layer 1 [...] input_cyan.jpg hatched --layer 2 [...] input_magenta.jpg hatched --layer 3 [...] input_yellow.jpg hatched --layer 4 [...] input_black.jpg show
```

**Comment by mariana-s-fernandes** [comment]
> I wonder if you can make x,y for circular, not always the middle of the art work.

I think what @joker999 meant was to have the center of the circle in an arbitrary position instead of the center of the image.
Thanks for the tip on the cmyk!

**Comment by mariana-s-fernandes** [comment]
I have implemented the changes for the center of the circles locally. Seems quite straightforward. I will open a PR with this.

**Comment by mariana-s-fernandes** [comment]
Implemented in https://github.com/plottertools/hatched/pull/8
