### ISSUE TITLE
Feature requests: variable number of layers, cross hatching and angle control, contour

### ISSUE THREAD

**Issue by mariana-s-fernandes** [abey79/hatched#6]
- It would be nice to have more than 3 levels (maybe a max of 5) to have more shadows 👍🏼 
- Accept different angles for the hatching (for example define one for all layers or one per layer) 👍🏼 
- Support cross hatching
- Option to draw contours

**Comment by abey79** [comment]
Hey @mariana-s-fernandes. Those would all be very nice to have indeed. However, for the foreseeable future, I will realistically be focusing on my main projects (vpype & vsketch). I can only encourage anyone to take on any or all of those and I'll happily take PR 👍🏻

**Comment by mariana-s-fernandes** [comment]
I will try my best, ~~I am starting with more layers~~ :)

**Comment by mariana-s-fernandes** [comment]
Note: I have the cross hatching done locally, didn't had the opportunity to create a PR yet since I am working on other stuff

**Comment by joshy** [comment]
Hi @mariana-s-fernandes, could you please sent me the code / patch? I am interested in cross hatching and will try to do a PR.

**Comment by mariana-s-fernandes** [comment]
Hi @joshy , if I recall, I think you can use this code and change the angles of the different levels to create the cross hatch effect

**Comment by mariana-s-fernandes** [comment]
I am closing this issue
